#
# Local site settings
remote_theme: wet-boew/gcweb-jekyll
title: "GCWeb, the Canada.ca official theme" # Site name or title
global:
  lang: en
  minifiedSuffix: ".min" 
  applicationURL:
    en: "#"
    fr: "#"

# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
      pageclass: oag-theme cnt-wdth-lmtd
      lang: en

#
# Jekyll settings
timezone: America/Toronto # Timezone for blog posts and alike

include:
  - assets

#
# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE*
- SECURITY.md
- Gruntfile.js
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- node_modules
- package.json
- package-lock.json
- .gitignore
- .gitmodules
- postcss.config.js
- npm-debug.log
- dist
